photo_ids: dict[str, str] = {
    'id1': 'AgACAgIAAxkBAAImqWaT-mSqPBNVAuWh759d8GPj9D85AALa2jEbcIegSCdv6yS0KVZWAQADAgADeQADNQQ',
    'cat': 'AgACAgIAAxkBAAIm-2aUMpVR-rBv_7fhsXmcDuHovYBXAAIg3DEbcIegSAABzpmLykjQRAEAAwIAA3gAAzUE',
    'PB': 'AgACAgIAAxkBAAInnGaYQFeUeAWOgAbJo0j-wywTC9voAAKW5DEb7CnBSIgkaaZ-rQ13AQADAgADeQADNQQ',
    'facults': 'AgACAgIAAxkBAAIsCmapZ5dt14Hz45Kg9c9xM84neD1qAALx4zEbiTlISdT5_igWi7jDAQADAgADeQADNQQ',
    'shops': 'AgACAgIAAxkBAAIqCGapOA1UD0qLBWpZxD2J7r51kuMXAAIH4zEbiTlISYsUHXkzmQfaAQADAgADeQADNQQ',
    'cafe': 'AgACAgIAAxkBAAIqxmapOg2-dF0umIG11bPNxqo2bPcOAAIX4zEbiTlISR9RPJTeBOX6AQADAgADeQADNQQ',
    'campus': 'AgACAgIAAxkBAAIsEmapaRwBaBf0yxi-z04L4YzSHkfJAALz4zEbiTlISfQrC1qSCG-oAQADAgADeQADNQQ',
    'room': 'AgACAgIAAxkBAAIsPGapeT3jM7J6mbwVxXg6MH1D1EtVAAIT5DEbiTlISV8WejsDf0B4AQADAgADeQADNQQ',
    'park': 'AgACAgIAAxkBAAItN2arx3G91DE9UJsp8Pdbkla93FxuAAJE3zEb4sNhSX0qXH70Sl5tAQADAgADeQADNQQ',
    'LSS': 'AgACAgIAAxkBAAItQWaryIOwRfV2CeDrhK_97NI4Ad_UAAJS3zEb4sNhSZCOIWOeBgWIAQADAgADeAADNQQ',
    'durka': 'AgACAgIAAxkBAAItn2ar9iDaBJk-lsHtlnuZheFw9ON4AALi4DEb4sNhSZ63la6G_4wFAQADAgADeAADNQQ',
    '1fl': 'AgACAgIAAxkBAAI0XGaynyJDxHUH8epu1I4C4t7WS2hiAAIX3zEbIN2ZSf_lNQJK145MAQADAgADdwADNQQ',
    '2fl': 'AgACAgIAAxkBAAI0Wmaynx3v8boNlVDgN-FOs8TgLOqTAAIW3zEbIN2ZSZZFqVvxdijVAQADAgADdwADNQQ',
    '3fl': 'AgACAgIAAxkBAAI0WGaynxPByh68QNuM1HhqBt6cG5iiAAIV3zEbIN2ZSQcylWrNJCC8AQADAgADdwADNQQ',
    '4fl': 'AgACAgIAAxkBAAI0iGayp75xFOhkOdf2vbwmXm4l0LFXAAIi3zEbIN2ZSVBuTu7HNXTAAQADAgADeQADNQQ',
    'apt': 'AgACAgIAAxkBAAI2W2a7uXlAtFY_i6f0z731uEO1ONOLAAIv5jEbn0zZSQQy1Tv-yK0DAQADAgADeQADNQQ',
    'mendel': 'AgACAgIAAxkBAAI3e2a89HXnnw3-ayVhv6D1SXge2UhNAAKp4DEb7_LoSZmLeNVVSmYrAQADAgADeQADNQQ',
    'ten': 'AgACAgIAAxkBAAI3j2a89or-xiOvFqtEFlhHC7nbXigtAAK04DEb7_LoSbzdtqVHAad5AQADAgADeQADNQQ',
    'penkova': 'AgACAgIAAxkBAAIJmmb55_65zbYzrGWQ1EpCKhHZ54sYAAJ87jEb9zPQS7e_7ahed7vxAQADAgADeQADNgQ',
    'korz': 'AgACAgIAAxkBAAIJnGb56Isumxa8AxhfTB1UZXa7VWHzAAJ-7jEb9zPQS9wWlPuKgyhTAQADAgADeQADNgQ',
    'osmol': 'AgACAgIAAxkBAAIJnmb56Qv8FEqlUMYyGBL8jonXc7NeAAJ_7jEb9zPQS6WcpMOKqaLlAQADAgADeQADNgQ',
    'bolot': 'AgACAgIAAxkBAAKCJGb57TBKgfyKsrYc2AtRlM8L1ju8AAKA7jEb9zPQS7qRZ2PC3KYYAQADAgADeAADNgQ',
    'tolstoy': 'AgACAgIAAxkBAAIJomb56dR4hHuqnGmMZBVQQ1GMkNydAAKB7jEb9zPQS8Vvc8Bl48QnAQADAgADeQADNgQ',
    'kinz': 'AgACAgIAAxkBAAIJpmb56nNhzooGlRaZ_PDUg2c9C7LSAAKC7jEb9zPQS_zhiIIzZQ8DAQADAgADeQADNgQ',
    'solov': 'AgACAgIAAxkBAAIJqGb56tDlMpmxpOpPsO4QsRVcQq16AAKD7jEb9zPQS5fuayqd817sAQADAgADeQADNgQ'
}
docs_ids: dict[str, str] = {
    'kio': 'BQACAgIAAxkBAAI--GbE-EhZq82-FDvr1hJE9VSpiZwnAAJeXAACe50oSjwL26MBHQu2NQQ'
}