photo_ids: dict[str, str] = {
    'id1': 'AgACAgIAAxkBAAImqWaT-mSqPBNVAuWh759d8GPj9D85AALa2jEbcIegSCdv6yS0KVZWAQADAgADeQADNQQ',
    'cat': 'AgACAgIAAxkBAAMDZv0pnoUat9zOhzyU2mHZdXpLb1EAAgHjMRvNcelLB8Di1BArKlsBAAMCAAN4AAM2BA',
    'PB': 'AgACAgIAAxkBAAMFZv0pvrI6oBXOPda-e-ciZGYRWKUAAgLjMRvNcelLLCbUD8pJ6XYBAAMCAAN5AAM2BA',
    'facults': 'AgACAgIAAxkBAAMHZv0p5amc-2VLH-6Ixe-6C8BX6sgAAgPjMRvNcelLg0MTXyBVn4IBAAMCAAN5AAM2BA',
    'shops': 'AgACAgIAAxkBAAMJZv0p8_WiwGTRLE0uLzK8UZ-1oYEAAgTjMRvNcelL_xpUlvTZFFcBAAMCAAN5AAM2BA',
    'cafe': 'AgACAgIAAxkBAAMLZv0p_3z-Ab_sZ3rQp027MOvYxcsAAgXjMRvNcelLqYwOnwywxgABAQADAgADeQADNgQ' ,
    'campus': 'AgACAgIAAxkBAAMTZv0rC6w76Ix1QqQrCDC-fLepTAcAAgzjMRvNcelLHiJ22GhfSV0BAAMCAAN5AAM2BA',
    'room': 'AgACAgIAAxkBAAMPZv0qrFYcDSrNdfMCIt-ciXcHab0AAgrjMRvNcelLCuQv7f3xrtkBAAMCAAN5AAM2BA',
    'park': 'AgACAgIAAxkBAAMzZv0sqo8xkaknZLX090hnB4SRyE4AAibjMRvNcelLhTHo6Ht2PJIBAAMCAAN5AAM2BA',
    'LSS': 'AgACAgIAAxkBAAMRZv0q36q9qIXfDVp6BOHrdw0nRBMAAgvjMRvNcelLklNCjOX_2GkBAAMCAAN4AAM2BA',
    'durka': 'AgACAgIAAxkBAAMNZv0qacBKy7HI2uFWu2TGl2eDmPkAAgnjMRvNcelL7xe9WDR6OB8BAAMCAAN4AAM2BA',
    '1fl': 'AgACAgIAAxkBAAMVZv0rOTgavkkwlDCSBpi-pTJuhe0AAg3jMRvNcelLKU3DqxX0h-EBAAMCAAN3AAM2BA',
    '2fl': 'AgACAgIAAxkBAAMXZv0rPyX51FGP01dqfmd-5HNUvMsAAg7jMRvNcelLrob4iVjhS5ABAAMCAAN3AAM2BA',
    '3fl': 'AgACAgIAAxkBAAMZZv0rRKeEBsagnKzot3uVYy753LMAAg_jMRvNcelLy5PDdqOJMwsBAAMCAAN3AAM2BA',
    '4fl': 'AgACAgIAAxkBAAMbZv0rSeHF9hnTS_VTzY5on8DxKuEAAhDjMRvNcelLekcglFSQ8dcBAAMCAAN5AAM2BA',
    'apt': 'AgACAgIAAxkBAAMdZv0ro05azugy_XehTpYYr1ouZJgAAhHjMRvNcelLlCWFyA4Zkj0BAAMCAAN5AAM2BA',
    'mendel': 'AgACAgIAAxkBAAMfZv0rx4yuBTegXvz7lgABcCns3NDtAAIT4zEbzXHpS7R8QZ-WiWkqAQADAgADeQADNgQ',
    'ten': 'AgACAgIAAxkBAAMhZv0rzCJ2BP1vzFAI_i5lBFY5YPEAAhTjMRvNcelLMmR21z6nqnsBAAMCAAN5AAM2BA',
    'penkova': 'AgACAgIAAxkBAAMjZv0r5qud4zNzIBipJ57-YOx5JTgAAhfjMRvNcelLah1mj3hNlwgBAAMCAAN5AAM2BA',
    'korz': 'AgACAgIAAxkBAAMlZv0r6t3Rigo4ItuQshYjjukSWD4AAhrjMRvNcelL6Sl6SbC3iuwBAAMCAAN5AAM2BA',
    'osmol': 'AgACAgIAAxkBAAMnZv0r8TF5f-R0pNMJxDdnYmp1FZsAAhvjMRvNcelLfVlSLanfTJABAAMCAAN5AAM2BA',
    'bolot': 'AgACAgIAAxkBAAMpZv0r9-evu-LKv940VbEi434i0NEAAhzjMRvNcelLnHGdiQ6dtnEBAAMCAAN4AAM2BA' ,
    'tolstoy': 'AgACAgIAAxkBAAMrZv0r_PVpK6xbBTg0u9T5u0YnCnUAAh3jMRvNcelLMEPhsVzsOpEBAAMCAAN5AAM2BA',
    'kinz': 'AgACAgIAAxkBAAMtZv0r_cgAAfYql96x0_762OeA28W8AAIe4zEbzXHpS52aVVFTLtpuAQADAgADeQADNgQ',
    'solov': 'AgACAgIAAxkBAAMvZv0sAXL-uKLahnlZ7xyEpEYAAYXAAAIf4zEbzXHpSyIg6plA25fxAQADAgADeQADNgQ',
    'kirs': 'AgACAgIAAxkBAAMxZv0sCGNAGZtSQkvMKtZUtpnZfA0AAiDjMRvNcelLeiuLftF4TYgBAAMCAAN5AAM2BA',
    'SS': 'AgACAgIAAxkBAAIedWdAiA9_dLi8vpNzd1__oSWur4PoAALa5TEbpg0ISh1f12ngs-LnAQADAgADeQADNgQ'
}
docs_ids: dict[str, str] = {
    'kio': 'BQACAgIAAxkBAAI--GbE-EhZq82-FDvr1hJE9VSpiZwnAAJeXAACe50oSjwL26MBHQu2NQQ'
}